---
 - name: php extension install
   apt: name={{item}} state=present force=yes
   with_items:
       - php-http
       - php5-dev
       - libcurl3
       - libcurl4-openssl-dev

# - name: http install
#   shell: pecl install pecl_http-1.7.6

 - name: php config
   action: template src=templates/php.ini dest=/etc/php5/apache2/php.in

 - name: apache2 restarted
   service: name=apache2 state=restarted
   
